SuperheroesProject/SuperheroesProject/urls.py
# from SuperheroesProject import superheroes
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('superheroes/', include('superheroes.urls')),
    path('', RedirectView.as_view(url='/superheroes/'))
]

SuperheroesProject/superheroes/urls.py
from django.urls import path
from . import views

app_name = 'superheroes'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:superhero_id>/', views.detail, name='detail'),
    path('new/', views.create, name='create_new_superhero')
    ]

SuperheroesProject/superheroes/models.py
from django.db import models

# Create your models here.

class Superhero(models.Model):
    name = models.CharField(max_length=50)
    alter_ego = models.CharField(max_length=50)
    primary_superhero_ability = models.CharField(max_length=50)
    secondary_superhero_ability = models.CharField(max_length=50)
    catchphrase = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name

SuperheroesProject/superheroes/views.py
from django.shortcuts import render
from .models import Superhero
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

# Create your views here.



def index(request):
    all_superheroes = Superhero.objects.all()
    context = {
        'all_superheroes': all_superheroes
    }
    return render(request, 'superheroes/index.html', context)

def detail(request, superhero_id):
    a_hero = Superhero.objects.get(pk=superhero_id)
    context = {
        'a_hero': a_hero
    }
    return render(request, 'superheroes/details.html', context)

def create(request):
    if request.method == "POST":
        name = request.POST.get('name')
        alter_ego = request.POST.get('alter_ego')
        primary_superhero_ability = request.POST.get('primary_superhero_ability')
        secondary_superhero_ability = request.POST.get('secondary_superhero_ability')
        catchphrase = request.POST.get('catchphrase')
        new_superhero = Superhero(name=name, alter_ego=alter_ego, primary_superhero_ability=primary_superhero_ability, 
                                  secondary_superhero_ability=secondary_superhero_ability, catchphrase=catchphrase)
        new_superhero.save()
        return HttpResponseRedirect(reverse('superheroes:index'))
    else:
        return render(request, 'superheroes/create.html')

SuperheroesProject/superheroes/templates/superheroes/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create a superhero!</title>
</head>
<body>
    <form action ="{% url 'superheroes:create_new_superhero' %}" method="post">
        {% csrf_token %}
        Name:<input type ="text" name="name" id="name"><br>
        Alter Ego:<input type="text" name="alter_ego" id="alter_ego"><br>
        Primary Superhero Ability:<input type="text" name="primary_superhero_ability" id="primary_superhero_ability"><br>
        Secondary Superhero Ability:<input type="text" name="secondary_superhero_ability" id="secondary_superhero_ability"><br>
        Catchphrase:<input type="text" name="catchphrase" id="catchphrase"><br>
        <input type="submit" value="Add new!">


        

    </form>
    
</body>
</html>

SuperheroesProject/superheroes/templates/superheroes/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hero Details</title>
</head>
<body>
    <h1>
        Hero Details
    </h1>
    <ul>
        <li>Name: {{a_hero.name}}</li>
        <li>Alter Ego: {{a_hero.alter_ego}}</li>
        <li>Primary Ability: {{a_hero.primary_superhero_ability}}</li>
        <li>Secondary Ability: {{a_hero.secondary_superhero_ability}}</li>
        <li>Catchphrase: {{a_hero.catchphrase}}</li>
            
            
        
    </ul>
</body>
</html>

SuperheroesProject/superheroes/templates/superheroes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Superhero Index</title>
</head>
<body>
    <h1>
        List of Superheroes
    </h1>
    <ul>
        {% for superhero in all_superheroes %}
        <li><h2> {{superhero.name}} </h2>
            <a href="{% url 'superheroes:detail' superhero.id %}">See more info</a></li>
        {% endfor %} 
    </ul>
</body>
</html>